import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "AI Playground",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<TooltipProvider>
				<body
					className={cn(
						"bg-background font-sans antialiased flex",
						inter.className
					)}
				>
					<Navbar />
					<main className="flex-1">{children}</main>
				</body>
			</TooltipProvider>
		</html>
	);
}
